### ISSUE TITLE
Option to provide only schema-url?

### ISSUE THREAD

**Issue by c2bo** [vcstuff/sd-jwt-vc-types#1]
I just finished my first read of the draft and it feels like the overall concept makes a lot of sense as a general approach for credential type metadata! The main thing I was wondering about when reading the draft was if this is really necessary for every credential or if sometimes only providing some kind of schema information would be sufficient.

Do you think it makes sense to also allow an option where the `vct` claim directly references a schema (perhaps including the integrity information)? This could be a lightweight version where the credential issuer will not provide additional metadata but wants to convey at least the schema (most likely an external URL).

**Comment by danielfett** [comment]
Just for clarification, by schema you mean the JSON schema?

**Comment by c2bo** [comment]
> Just for clarification, by schema you mean the JSON schema?

Yes. I am wondering if we always need/want the full metadata or if sometimes just a JSON schema reference would be fine. Basically a subset of information that does not require some kind of .well-known ressource.

**Comment by c2bo** [comment]
I am just reading the new updated version and I guess this would be mostly solved by the new Glue section --> I think we can close this.

**Comment by danielfett** [comment]
Thank you!
