### ISSUE TITLE
Improvements to example

### ISSUE THREAD

**Issue by jogu** [vcstuff/sd-jwt-vc-types#2]
A couple of things I spotted about the example:

1. I think it's defining a credential for all Betelgeuse universities, but the example logo implies it's only for a single university: "https://exampleuniversity.com/public/logo.png" - "https://betelgeuse.example.com/education-logo.png" might be better
2. There isn't a logo defined for de-DE, which seems inconsistent with Section 7 ("Display Metadata") as there are claim display names defined for de-DE: "The object MUST contain a property for each language that is supported by the type"
3. The vct of "https://betelgeuse.example.com/identity_credential" - I'm not sure 'identity_credential' is a good description for the contents, maybe "https://betelgeuse.example.com/degree_credential" is better (I think it's not an identity credential with an optional degree, because if it was the name would be authoritative and it would probably allow multiple degrees to be listed)
4. The formatting is a bit messed up in the rendered example in general as there's a mixture of spaces/tabs

**Comment by danielfett** [comment]
Thanks! https://github.com/vcstuff/sd-jwt-vc-types/pull/3
